---
- name: JUnit Report Test
  hosts: hosts
  gather_facts: true

  tasks:
    - name: Sample assertion
      assert:
        that:
          - "'foo' in 'foobar'"
        fail_msg: "Test failed: 'foo' is not in 'foobar'"
        success_msg: "Test passed: 'foo' is in 'foobar'"
      register: sample_assertion_result

    # Get current date and time on control machine
    - name: Get current date and time on control machine
      command: date "+%Y-%m-%d-%H-%M-%S"
      delegate_to: localhost
      register: current_date
      run_once: true

    - set_fact:
        timestamp: "{{ current_date.stdout }}"

    - name: Ensure destination directory exists
      file:
        path: /tmp/reports2
        state: directory
        mode: '0755'
      delegate_to: localhost

    - name: Report Sample Assertion Result for JUnit
      debug:
        msg: "Sample assertion, Result: {{ sample_assertion_result.msg }}"
      when: sample_assertion_result is defined

    - name: Generate report text
      local_action:
        module: copy
        content: "{{ sample_assertion_result.msg }}"
        dest: "/tmp/reports2/junit-test-{{ timestamp }}.txt"  # Changed to .txt to differentiate it from junit's .xml
      when: sample_assertion_result is defined
