---
- name: Check Timezone on Windows Host
  hosts: hosts
  tasks:
    # Ensure the report directory exists
    - name: Ensure reports directory exists
      local_action: 
        module: file
        path: "/home/tychon/reports"
        state: directory
        mode: '0777'

    - name: Get the current time zone
      win_shell: (Get-TimeZone).Id
      register: timezone_result

    - name: Assert timezone is Eastern Standard Time
      assert:
        that:
          - "timezone_result.stdout | trim == 'Eastern Standard Time'"
        fail_msg: "The timezone is not set to Eastern Standard Time. Found: {{ timezone_result.stdout | trim }}"
        success_msg: "The timezone is set to Eastern Standard Time."

    - name: Save result as JUnit XML
      delegate_to: localhost
      template:
        src: windows-timezone-text.j2
        dest: "/home/tychon/reports/timezone_report.xml"
