---
- hosts: hosts
  tasks:
    # Apply updates and reboot if necessary
    # - name: Performing Windows updates...
    #   win_updates:
    #   register: update_result

    # - debug: var=update_result.stdout_lines

    - name: Reboot the Windows host
      win_reboot:
        msg: "Rebooting the host as it is required after updating..."
      #when: update_result.reboot_required