---
- name: JUnit Report Test
  hosts: hosts
  gather_facts: true

  tasks:
    - name: Sample assertion
      assert:
        that:
          - "'foo' in 'foobar'"
        fail_msg: "Test failed: 'foo' is not in 'foobar'"
        success_msg: "Test passed: 'foo' is in 'foobar'"
      register: result

    # Get current date and time on control machine
    - name: Get current date and time on control machine
      command: date "+%Y-%m-%d-%H-%M-%S"
      delegate_to: localhost
      register: current_date
      run_once: true

    - set_fact:
        timestamp: "{{ current_date.stdout }}"

    - name: Ensure destination directory exists
      file:
        path: /tmp/semaphore_reports
        state: directory
        mode: '0755'
      delegate_to: localhost

    - name: Generate report
      local_action:
        module: copy
        content: "{{ result.fail_msg if result.failed else 'All tests passed' }}"
        dest: "/tmp/semaphore_reports/junit-test-{{ timestamp }}.yml"
      when: result is defined


