---
- name: Windows Performance Monitoring
  hosts: windows
  gather_facts: no
  vars:
    cpu_threshold: 90

  tasks:
  
    - name: Collect CPU Usage
      win_shell: |
        $cpuLoad = Get-WmiObject win32_processor | Measure-Object -property LoadPercentage -Average | Select Average
        return $cpuLoad.Average
      register: cpu_result

    - name: Collect Memory Usage
      win_shell: |
        $freeMemory = Get-WmiObject -Class Win32_OperatingSystem | Select-Object @{Name="FreeMemory";Expression={$_.FreePhysicalMemory/1KB}}
        return $freeMemory.FreeMemory
      register: memory_result

    - name: Collect Disk Usage
      win_shell: |
        $diskUsage = Get-WmiObject -Class Win32_LogicalDisk -Filter "DriveType=3" | Select-Object DeviceID, @{Name="UsedSpace";Expression={"{0:N2}" -f (($_.Size - $_.FreeSpace)/1GB)}}
        return $diskUsage
      register: disk_result

    - name: Collect Network Usage
      win_shell: |
        $network = Get-WmiObject -Class Win32_PerfRawData_Tcpip_NetworkInterface
        return $network
      register: network_result

    - name: Analyze and Create Report
      set_fact:
        report:
          cpu_usage: "{{ cpu_result.stdout | int }}"
          memory_free: "{{ memory_result.stdout | int }}"
          disk_usage: "{{ disk_result.stdout_lines }}"
          network_usage: "{{ network_result.stdout_lines }}"
      
    - name: Display Report
      debug:
        var: report
      
    - name: Check for anomalies in CPU Usage and Alert
      fail:
        msg: "ALERT! CPU usage is high: {{ cpu_result.stdout }}%"
      when: cpu_result.stdout | int > cpu_threshold
