---
- name: Check Timezone on Windows Host
  hosts: hosts
  tasks:
    # Ensure the report directory exists
    - name: Ensure reports directory exists
      local_action:
        module: file
        path: "/tmp/reports"
        state: directory
        mode: '0777'

    - name: Get the current time zone
      win_shell: (Get-TimeZone).Id
      register: timezone_result

    - name: Assert timezone is Eastern Standard Time
      assert:
        that:
          - "timezone_result.stdout | trim == 'Eastern Standard Time'"
        fail_msg: "The timezone is not set to Eastern Standard Time. Found: {{ timezone_result.stdout | trim }}"
        success_msg: "The timezone is set to Eastern Standard Time."
      ignore_errors: true
      register: assert_result

    # Capture hostname and datetime
    - name: Get local datetime
      delegate_to: localhost
      set_fact:
        current_datetime: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"

    - name: Get target hostname
      win_shell: hostname
      register: target_hostname

    # Save the result as a JUnit XML file with the updated name
    - name: Save result as JUnit XML
      delegate_to: localhost
      template:
        src: windows-timezone-test.j2
        dest: "/tmp/reports/timezone_report_{{ target_hostname.stdout | trim }}_{{ current_datetime }}.xml"
