---
- name: Check if TimeZone is Eastern Standard
  hosts: hosts
  gather_facts: no
  tasks:
    - name: Ensure C:\temp directory exists on Windows host
      win_file:
        path: "C:\\temp"
        state: directory
  
    - name: Get current time zone
      win_timezone:
        name: "USE_EXISTING"
      register: timezone_status

    - name: Determine if the timezone is Eastern Standard Time
      set_fact:
        is_est: "{{ timezone_status.name == 'Eastern Standard Time' }}"
  
    - name: Generate JUnit formatted output for EST
      win_shell: |
        if ({{ is_est }}) {
            $testStatus = 'pass'
            $message = '<system-out>Timezone is Eastern Standard Time</system-out>'
        } else {
            $testStatus = 'fail'
            $message = "<failure>Timezone is not Eastern Standard Time. It's set to {{ timezone_status.name }}</failure>"
        }

        $xmlContent = @"
        <?xml version="1.0" encoding="UTF-8"?>
        <testsuite name="TimeZoneCheck" tests="1">
            <testcase classname="Windows" name="IsEasternStandardTime">
                $message
            </testcase>
        </testsuite>
        "@

        $xmlContent | Out-File -Encoding utf8 "C:\temp\timezone_test_result.xml"

    - name: Fetch JUnit results to the Ansible controller
      fetch:
        src: "C:\\temp\\timezone_test_result.xml"
        dest: "/tmp/reports/timezone_test_result.xml"
        flat: yes
  
  # Run tasks on localhost to prepare the Ansible controller
  post_tasks:
    - name: Ensure /tmp/reports directory exists on Ansible controller
      file:
        path: "/tmp/reports"
        state: directory
      delegate_to: localhost
