---
- name: JUnit Report Test
  hosts: hosts
  gather_facts: true  # Gather facts to get ansible_date_time from remote hosts

  tasks:
    - name: Sample assertion
      assert:
        that:
          - "'foo' in 'foobar'"
        fail_msg: "Test failed: 'foo' is not in 'foobar'"
        success_msg: "Test passed: 'foo' is in 'foobar'"
      register: result

    # Setting the timestamp variable on the control node
    - set_fact:
        timestamp: "{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}-{{ ansible_date_time.second }}"
      delegate_to: localhost
      run_once: true

    - name: Generate report
      local_action:
        module: copy
        content: "{{ result.fail_msg if result.failed else 'All tests passed' }}"
        dest: "/tmp/semaphore_reports/junit-test-{{ timestamp }}.yml"
      when: result is defined

